<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Miscellaneous language phrases


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
    'block_ip_button'           => 'Az IP-cím blokkolása',
    'browse_categories'         => 'Kategóriák böngészése',
    'captcha_approve_fix'       => 'Ez az ellenőrzés nem jelenik meg a fiók elfogadása után.',
    'captcha_confirm_fix'       => 'A jövőbeni ellenőrzések elkerülése érdekében kérjük ^5erősítsd meg email címed^6.',
    'captcha_error'             => 'Kérjük végezd el az anti-spam ellenőrzést',
    'captcha_label'             => 'Anti-spam ellenőrzés:',
    'captcha_login_fix'         => 'A jövőbeni ellenőrzések elkerülése érdekében kérjük ^1jelentkezz be^2 vagy ^3regisztrálj^4.',
    'feed_a_edited_prefix'      => 'Válasz szerkesztve: ',
    'feed_a_prefix'             => 'Megválaszolva: ',
    'feed_a_reshown_prefix'     => 'Válasz újramegjelenítve: ',
    'feed_a_selected_prefix'    => 'Válasz kiválasztva: ',
    'feed_c_edited_prefix'      => 'Hozzászólás szerkesztve: ',
    'feed_c_moved_prefix'       => 'Hozzászólás áthelyezve: ',
    'feed_c_prefix'             => 'Hozzászólt: ',
    'feed_c_reshown_prefix'     => 'Hozzászólás újramegjelenítve: ',
    'feed_closed_prefix'        => 'Bezárt: ',
    'feed_edited_prefix'        => 'Szerkesztve: ',
    'feed_hidden_prefix'        => 'Rejtett: ',
    'feed_not_found'            => 'Nem található feed',
    'feed_recategorized_prefix' => 'Újrakategorizált: ',
    'feed_reopened_prefix'      => 'Újrakinyitva: ',
    'feed_reshown_prefix'       => 'Újramegjelenítve: ',
    'feed_retagged_prefix'      => 'Újracímzett: ',
    'feedback_email'            => 'Email cím az admin üzenetekhez - nem jelenik meg a felhasználóknak:',
    'feedback_empty'            => 'Kérjük használd ezt a mezőt néhány hozzászólás vagy javaslat elküldéséhez',
    'feedback_message'          => 'Véleményed vagy javaslatod a ^ témával kapcsolatban:',
    'feedback_name'             => 'Név: (nem kötelező)',
    'feedback_sent'             => 'Az alábbi üzeneted elküldve - köszönjük.',
    'feedback_title'            => 'Visszajelzés küldése',
    'form_security_again'       => 'Kérjük kattints ismét a megerősítéshez',
    'form_security_reload'      => 'Kérjük frissítsd az oldalt, majd próbáld újra',
    'hide_all_ip_button'        => 'Az összes poszt elrejtése erről az IP-től',
    'host_name'                 => 'Hostnév:',
    'inbox'                     => 'Beérkező üzenetek',
    'matches_blocked_ips'       => 'Egyezik a blokkolt IP-címekkel:',
    'message_empty'             => 'Kérjük írd be az üzenetet, amit ennek a felhasználónak szeretnél küldeni',
    'message_explanation'       => 'Ezt értesítésként fogjuk elküldeni a ^ felhasználótól. Az email címed nem jelenik meg, hacsak nem írod le az üzenetben.',
    'message_for_x'             => 'Üzeneted ^ felhasználónak:',
    'message_limit'             => 'Nem küldhetsz több privát üzenetet ebben az órában',
    'message_must_login'        => 'Privát üzenetküldéshez kérjük ^1jelentkezz be^2 vagy ^3regisztrálj^4.',
    'message_recent_history'    => 'Legutóbbi levelezésed ^ felhasználóval',
    'message_sent'              => 'Az alábbi privát üzeneted elküldve',
    'more_favorite_qs'          => 'További kedvenc kérdések...',
    'more_favorite_tags'        => 'További kedvenc címkék...',
    'more_favorite_users'       => 'További kedvenc felhasználók...',
    'my_favorites_title'        => 'Kedvenceim',
    'nav_all_my_updates'        => 'Értesítéseim',
    'nav_my_content'            => 'Saját tartalmam',
    'nav_my_details'            => 'Fiókom',
    'nav_my_favorites'          => 'Kedvenceim',
    'nav_user_activity'         => 'Legutóbbi tevékenység',
    'nav_user_as'               => 'Minden válasz',
    'nav_user_pms'              => 'Privát üzenetek',
    'nav_user_qs'               => 'Minden kérdés',
    'nav_user_wall'             => 'Fal',
    'next_step'                 => 'Következő lépés',
    'no_activity_from_x'        => 'Nincs tevékenység ^ felhasználótól',
    'no_favorite_categories'    => 'Nincsenek kedvenc kategóriák',
    'no_favorite_qs'            => 'Nincsenek kedvenc kérdések',
    'no_favorite_tags'          => 'Nincsenek kedvenc címkék',
    'no_favorite_users'         => 'Nincsenek kedvenc felhasználók',
    'no_recent_updates'         => 'Nincs új értesítés',
    'no_updates_content'        => 'Nincs új értesítés a saját tartalmaimhoz',
    'no_updates_favorites'      => 'Nincs új értesítés a kedvenceimhez',
    'outbox'                    => 'Elküldött üzenetek',
    'pm_inbox_title'            => 'Privát üzenetek érkeztek',
    'pm_outbox_title'           => 'Privát üzenetek elküldve',
    'private_message_title'     => 'Privát üzenet küldése',
    'recent_activity_from_x'    => 'Legutóbbi tevékenység ^ felhasználótól',
    'recent_updates_content'    => 'Legutóbbi értesítések a saját tartalmaimhoz',
    'recent_updates_favorites'  => 'Legutóbbi értesítések a kedvenceimhez',
    'recent_updates_title'      => 'Legutóbbi értesítéseim',
    'site_in_maintenance'       => 'Ez az oldal jelenleg karbantartás alatt van - kérjük térj vissza kicsit később.',
    'suggest_favorites_add'     => 'Ha kérdést vagy más elemet szeretnél hozzáadni a kedvenceidhez, kattints az oldal tetején lévő ^ elemre.',
    'suggest_update_favorites'  => 'További értesítésekért adj hozzá tartalmat a ^1kedvenceidhez^2.',
    'unblock_ip_button'         => 'IP cím feloldása',
    'your_a_commented'          => 'a te válaszod hozzászólással',
    'your_a_edited'             => 'a te válaszod szerkesztéssel',
    'your_a_hidden'             => 'a te válaszod elrejtve',
    'your_a_questioned'         => 'a te válaszodon kérdezve',
    'your_a_reshown'            => 'a te válaszod újramegjelenítve',
    'your_a_selected'           => 'a te válaszod kiválasztva',
    'your_c_edited'             => 'a te hozzászólásod szerkesztéssel',
    'your_c_followed'           => 'a te hozzászólásod követve',
    'your_c_hidden'             => 'a te hozzászólásod elrejtve',
    'your_c_moved'              => 'a te hozzászólásod elhelyezve',
    'your_c_reshown'            => 'a te hozzászólásod újramegjelenítve',
    'your_q_answered'           => 'a te kérdésed megválaszolva',
    'your_q_closed'             => 'a te kérdésed lezárva',
    'your_q_commented'          => 'a te kérdésed hozzászólással',
    'your_q_edited'             => 'a te kérdésed szerkesztéssel',
    'your_q_hidden'             => 'a te kérdésed elrejtve',
    'your_q_recategorized'      => 'a te kérdésed újrakategórizálva',
    'your_q_reopened'           => 'a te kérdésed újrakinyitva',
    'your_q_reshown'            => 'a te kérdésed újramegjelenítve',
    'your_q_retagged'           => 'a te kérdésed újramegcímkézve',
);
