<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
    '_decimal_point'             => ',',
    '_thousands_separator'       => '.',
    '_thousands_suffix'          => 'e',
    '_millions_suffix'           => 'M',
    '1_answer'                   => '1 válasz',
    '1_comment'                  => '1 hozzászólás',
    '1_day'                      => '1 nap',
    '1_disliked'                 => '1 dislike',
    '1_flag'                     => '1 jelentés',
    '1_hour'                     => '1 óra',
    '1_liked'                    => '1 like',
    '1_minute'                   => '1 perc',
    '1_month'                    => '1 hónap',
    '1_point'                    => '1 pont',
    '1_question'                 => '1 kérdés',
    '1_second'                   => '1 másodperc',
    '1_tag'                      => '1 címke',
    '1_user'                     => '1 felhasználó',
    '1_view'                     => '1 megtekintés',
    '1_vote'                     => '1 szavazat',
    '1_week'                     => '1 hét',
    '1_year'                     => '1 év',
    'add_category_x_favorites'   => '^ kategória hozzáadása a kedvenceimhez',
    'add_favorites'              => 'Hozzáadás a kenvenceimhez',
    'add_tag_x_favorites'        => '^ címke hozzáadása a kedvenceimhez',
    'all_categories'             => 'Minden kategória',
    'anonymous'                  => 'névtelen',
    'answer_edited'              => 'szerkesztett válasz',
    'answer_reshown'             => 'válasz újramegjelenítve',
    'answer_selected'            => 'válasz kiválasztva',
    'answered'                   => 'válaszolt',
    'answered_qs_in_x'           => 'Legtöbb válasszal rendelkező kérdések a(z) ^ kategóriában',
    'answered_qs_title'          => 'Legtöbbször megválaszolt kérdések',
    'asked'                      => 'kérdezett',
    'asked_related_q'            => 'kapcsolódó kérdést tett fel',
    'by_x'                       => '^ által',
    'cancel_button'              => 'Mégse',
    'closed'                     => 'bezárt',
    'comment_edited'             => 'szerkesztett hozzászólás',
    'comment_moved'              => 'hozzászólás áthelyezve',
    'comment_reshown'            => 'hozzászólás újramegjelenítve',
    'commented'                  => 'hozzászólt',
    'date_day_min_digits'        => '1', // 1 or 2
    'date_format_other_years'    => '^year. ^month. ^day.',
    'date_format_this_year'      => '^month ^day',
    'date_month_1'               => 'jan',
    'date_month_2'               => 'febr',
    'date_month_3'               => 'márc',
    'date_month_4'               => 'ápr',
    'date_month_5'               => 'máj',
    'date_month_6'               => 'jún',
    'date_month_7'               => 'júl',
    'date_month_8'               => 'aug',
    'date_month_9'               => 'szept',
    'date_month_10'              => 'okt',
    'date_month_11'              => 'nov',
    'date_month_12'              => 'dec',
    'date_year_digits'           => '4',
    'edited'                     => 'szerkesztett',
    'email_error'                => 'Hiba történt az email elküldésével.',
    'field_required'             => 'Kérjük írj valamit a mezőbe',
    'file_upload_limit_exceeded' => 'A fájl mérete meghaladja a szerver korlátait',
    'general_error'              => 'Szerverhiba történt - próbálkozz újra.',
    'hidden'                     => 'rejtett',
    'highest_users'              => 'A legmagasabb pontszámú felhasználók',
    'hot_qs_in_x'                => 'Trendi kérdések itt: ^',
    'hot_qs_title'               => 'Trendi kérdések',
    'image_not_read'             => 'Nem lehetett elolvasni a képet. Tölts fel egyet az alábbiakból: ^',
    'image_too_big_x_pc'         => 'Túl nagy a kép. Méretezd át ^% nagyságúra, majd próbáld újra.',
    'in_category_x'              => 'a(z) ^ kategóriában',
    'ip_address_x'               => 'IP cím ^',
    'logged_in_x'                => 'Szia ^',
    'max_length_x'               => 'A maximális hosszúság ^ karakter',
    'max_upload_size_x'          => 'A feltöltés maximális mérete ^',
    'me'                         => 'nekem',
    'meta_order'                 => '^who^what^where^when // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>',
    'min_length_x'               => 'Kérjük adj meg több információt - legalább ^ karaktert',
    'moved'                      => 'áthelyezett',
    'nav_activity'               => 'Minden tevékenység',
    'nav_admin'                  => 'Admin',
    'nav_ask'                    => 'Tegyél fel egy kérdést',
    'nav_categories'             => 'Kategóriák',
    'nav_feedback'               => 'Visszajelzés küldése',
    'nav_home'                   => 'Főoldal',
    'nav_hot'                    => 'Trendi!',
    'nav_login'                  => 'Belépés',
    'nav_logout'                 => 'Kilépés',
    'nav_most_answers'           => 'Legtöbb válasz',
    'nav_most_recent'            => 'Friss',
    'nav_most_views'             => 'Legtöbb megtekintés',
    'nav_most_votes'             => 'Legtöbb szavazat',
    'nav_no_answer'              => 'Nincs válasz',
    'nav_no_selected_answer'     => 'Nincs kiválasztott válasz',
    'nav_no_upvoted_answer'      => 'Nincs felszavazott válasz',
    'nav_qa'                     => 'Q&A',
    'nav_qs'                     => 'Kérdések',
    'nav_register'               => 'Regisztráció',
    'nav_tags'                   => 'Címkék',
    'nav_unanswered'             => 'Megválaszolatlan',
    'nav_updates'                => 'Saját frissítések',
    'nav_users'                  => 'Felhasználók',
    'newest_users'               => 'Legújabb felhasználók',
    'no_active_users'            => 'Nincs aktív felhasználó',
    'no_answers_found'           => 'Nem található válasz',
    'no_answers_in_x'            => 'Nincs válasz itt: ^',
    'no_categories_found'        => 'Nem található kategória',
    'no_category'                => 'Nincs kategória',
    'no_comments_found'          => 'Nem található hozzászólás',
    'no_comments_in_x'           => 'Nincs hozzászólás itt: ^',
    'no_questions_found'         => 'Nem található kérdés',
    'no_questions_in_x'          => 'Nincs kérdés itt: ^',
    'no_related_qs_title'        => 'Nem található kapcsolódó kérdés',
    'no_results_for_x'           => 'Nincs találat a ^ kulcsszóra',
    'no_tags_found'              => 'Nem található címke',
    'no_una_questions_found'     => 'Nem található megválaszolatlan kérdés',
    'no_una_questions_in_x'      => 'Nincs megválaszolatlan kérdés itt: ^',
    'no_unselected_qs_found'     => 'Nem található kiválasztott válasz nélküli kérdés',
    'no_unupvoteda_qs_found'     => 'Nem található felszavazott válasz nélküli kérdés',
    'page_label'                 => 'Oldal:',
    'page_next'                  => 'következő',
    'page_not_found'             => 'Az oldal nem található',
    'page_prev'                  => 'előző',
    'popular_tags'               => 'A legnépszerűbb címkék',
    'questions_tagged_x'         => 'Legutóbbi ^ címkéjű kérdések',
    'recategorized'              => 'újrakategorizált',
    'recent_activity_in_x'       => 'Legutóbbi tevékenység itt: ^',
    'recent_activity_title'      => 'Legutóbbi tevékenység',
    'recent_as_in_x'             => 'Legutóbb megválaszolt kérdések itt: ^',
    'recent_as_title'            => 'Legutóbb megválaszolt kérdések',
    'recent_cs_in_x'             => 'Legutóbb hozzászólt kérdések itt: ^',
    'recent_cs_title'            => 'Legutóbb hozzászólt kérdések',
    'recent_qs_as_in_x'          => 'Legutóbbi kérdések és válaszok itt: ^',
    'recent_qs_as_title'         => 'Legutóbbi kérdések és válaszok',
    'recent_qs_in_x'             => 'Legutóbbi kérdések itt: ^',
    'recent_qs_title'            => 'Legutóbbi kérdések',
    'related_qs_title'           => 'Kapcsolódó kérdések',
    'remove_favorites'           => 'Törlés a kedvenceim közül',
    'remove_x_favorites'         => '^ törlése a kedvenceim közül',
    'reopened'                   => 'újranyitott',
    'reshown'                    => 'újramegjelenített',
    'results_for_x'              => '^ keresése az eredményekben',
    'retagged'                   => 'újracímkézett',
    'save_button'                => 'Változtatások mentése',
    'search_button'              => 'Keresés',
    'search_explanation'         => 'Írj valamit a keresőmezőbe, és próbálkozz újra.',
    'search_title'               => 'Keresési eredmények',
    'selected'                   => 'kiválasztott',
    'send_button'                => 'Küldés',
    'since_x'                    => '^ óta',
    'suggest_ask'                => 'Segíts beindítani a dolgokat, ^1tegyél fel egy kérdést^2!',
    'suggest_category_qs'        => 'Ha többet szeretnél látni, kattints: ^1kérdések ebben a kategóriában^2.',
    'suggest_qs'                 => 'Ha többet szeretnél látni, kattints: ^1teljes kérdéslista^2.',
    'suggest_qs_tags'            => 'Ha többet szeretnél látni, kattints a ^1teljes kérdéslista^2 vagy a ^3népszerű címkék^4 linkre.',
    'to_x'                       => '^ részére',
    'unanswered_qs_in_x'         => 'Válasz nélküli kérdések itt: ^',
    'unanswered_qs_title'        => 'Legutóbbi válasz nélküli kérdések',
    'unselected_qs_in_x'         => 'Kiválasztott válasz nélküli kérdések itt: ^',
    'unselected_qs_title'        => 'Legutóbbi kiválasztott válasz nélküli kérdések',
    'unupvoteda_qs_in_x'         => 'Felszavazott válasz nélküli kérdések itt: ^',
    'unupvoteda_qs_title'        => 'Legutóbbi felszavazott válasz nélküli kérdések',
    'upload_limit'               => 'Túl sok feltöltés - kérjük próbálkozz újra egy óra múlva',
    'view_q_must_be_approved'    => 'A kérdések oldalainak megtekintéséhez előbb el kell fogadjuk a fiókodat. Kérjük várj, vagy ^1 adj meg több információt^2.',
    'view_q_must_confirm'        => 'Kérjük ^5erősítsd meg az email címed^6 a kérdések oldalainak megtekintéséhez.',
    'view_q_must_login'          => 'Kérjük ^1jelentkezz be^2 vagy ^3regisztrálj^4 a kérdések oldalainak megtekintéséhez.',
    'viewed_qs_in_x'             => 'Legnézettebb kérdések itt: ^',
    'viewed_qs_title'            => 'Legnézettebb kérdések',
    'vote_disabled_approve'      => 'El kell fogadjuk a fiókodat, mielőtt szavazhatsz',
    'vote_disabled_down'         => 'A leszavazás csak bizonyos felhasználók számára érhető el',
    'vote_disabled_down_approve' => 'A leszavazó funkció használata előtt el kell fogadjuk a fiókodat',
    'vote_disabled_hidden_post'  => 'Rejtett posztokra nem szavazhatsz',
    'vote_disabled_hidden_a'     => 'Rejtett válaszokra nem szavazhatsz',  // @deprecated
    'vote_disabled_hidden_q'     => 'Rejtett kérdésekre nem szavazhatsz',  // @deprecated
    'vote_disabled_level'        => 'A szavazás csak bizonyos felhasználók számára elérhető',
    'vote_disabled_my_post'      => 'Saját posztjaidra nem szavazhatsz',
    'vote_disabled_my_a'         => 'Saját válaszaidra nem szavazhatsz',  // @deprecated
    'vote_disabled_my_q'         => 'Saját kérdéseidre nem szavazhatsz',  // @deprecated
    'vote_disabled_q_page_only'  => 'Szavazat leadásához kérjük előbb tekintsd meg a kérdést.',
    'vote_disabled_queued'       => 'Csak elfogadott posztokra szavazhatsz',
    'vote_down_must_confirm'     => 'Leszavazáshoz kérjük ^5erősítsd meg az email címed^6.',
    'vote_down_popup'            => 'Leszavazáshoz kattints ide',
    'vote_limit'                 => 'Túl sok szavazat érkezett - kérjük próbálkozz újra egy óra múlva',
    'vote_must_confirm'          => 'Szavazáshoz kérjük ^5erősítsd meg az email címed^6.',
    'vote_must_login'            => 'Szavazáshoz kérjük ^1jelentkezz be^2 vagy ^3regisztrálj^4.',
    'vote_not_allowed'           => 'Erre nem lehet szavazni',
    'vote_up_popup'              => 'Felszavazáshoz kattints ide',
    'voted_down_popup'           => 'Ezt leszavaztad - kattints a szavazat törléséhez',
    'voted_qs_in_x'              => 'Legjobbra értékelt kérdések itt: ^',
    'voted_qs_title'             => 'Legjobbra értékelt kérdések',
    'voted_up_popup'             => 'Ezt felszavaztad - kattints a szavazat törléséhez',
    'written'                    => 'írva',
    'x_ago'                      => '^ ezelőtt',
    'x_answers'                  => '^ válasz',
    'x_comments'                 => '^ hozzászólás',
    'x_days'                     => '^ nap',
    'x_disliked'                 => '^ dislike',
    'x_flags'                    => '^ jelentés',
    'x_hours'                    => '^ óra',
    'x_liked'                    => '^ like',
    'x_minutes'                  => '^ perc',
    'x_months'                   => '^ hónap',
    'x_points'                   => '^ pont',
    'x_questions'                => '^ kérdés',
    'x_seconds'                  => '^ másodperc',
    'x_tags'                     => '^ címke',
    'x_users'                    => '^ felhasználó',
    'x_views'                    => '^ megtekintés',
    'x_votes'                    => '^ szavazat',
    'x_weeks'                    => '^ hét',
    'x_years'                    => '^ év',
);
