<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for user management


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
    'about'                        => 'Névjegy',
    'add_user_x_favorites'         => '^ felhasználó hozzáadása a kedvenceimhez',
    'approve_required'             => 'Kérjük várd meg fiókod elfogadását vagy ^1adj meg további információt^2.',
    'approve_title'                => 'A felhasználó elfogadása függőben van',
    'approve_user_button'          => 'Felhasználó elfogadása',
    'approved_user'                => 'Elfogadott felhasználó',
    'avatar_default'               => 'Alapértelmezett',
    'avatar_gravatar'              => 'A ^1Gravatar^2-om mutatása',
    'avatar_label'                 => 'Avatar:',
    'avatar_none'                  => 'Nincs',
    'block_user_button'            => 'Felhasználó tiltása',
    'blocked_users'                => 'Letiltott felhasználók',
    'category_level_add'           => '- ^1kategória-specifikus jogosultságok hozzáadása^2',
    'category_level_in'            => 'az alábbi kategóriához:',
    'category_level_label'         => 'Frissített verzió:',
    'category_level_none'          => 'Nincs frissítés',
    'change_email_link'            => '- ^1email megváltoztatása^2',
    'change_password'              => 'Jelszó megváltoztatása',
    'confirm_button'               => 'Email cím megerősítése',
    'confirm_complete'             => 'Köszönjük - az email címed megerősítésre került.',
    'confirm_emailed'              => 'A megerősítő linket elküldtük emailben. Kérjük kattints a linkre, vagy írd be az alábbi mezőbe a megerősítési kódot az email címed megerősítéséhez.',
    'confirm_required'             => 'A regisztráció véglegesítéséhez kattints az emailben kapott megerősítő linkre, vagy ^1kérj egy másikat^2.',
    'confirm_title'                => 'Email cím megerősítése',
    'confirm_wrong_log_in'         => 'Hibás kód - kérjük ^1jelentkezz be^2 új hivatkozás küldéséhez.',
    'confirm_wrong_resend'         => 'Hibás kód - kattints az alábbi linkre új link küldéséhez.',
    'delete_user_button'           => 'Felhasználó törlése',
    'edit_profile'                 => 'Profil szerkesztése',
    'edit_user_button'             => 'Felhasználó szerkesztése',
    'email_code_another'           => 'új küldése',
    'email_code_emailed'           => 'A kódodat elküldtük az email címedre.',
    'email_code_label'             => 'Kód:',
    'email_code_wrong'             => 'Hibás kód',
    'email_confirmed'              => 'Elfogadva',
    'email_exists'                 => 'Ez az email cím már hozzá van rendelve egy fiókhoz',
    'email_handle_label'           => 'Email vagy felhasználónév:',
    'email_invalid'                => 'Hibás email - kérjük nézd át figyelmesen',
    'email_label'                  => 'Email:',
    'email_not_confirmed'          => 'Még nincs megerősítve',
    'email_please_confirm'         => 'Kérjük ^5erősítsd meg^6',
    'email_required'               => 'Email cím szükséges - nem publikus',
    'forgot_link'                  => 'Elfelejtettem a jelszavam',
    'full_name'                    => 'Teljes név',
    'handle_blocked'               => 'Felhasználónév nem megengedett - kérjük próbálkozz másikkal',
    'handle_empty'                 => 'Felhasználónév nem lehet üres',
    'handle_exists'                => 'Ez a felhasználónév már foglalt - kérjük próbálkozz másikkal',
    'handle_has_bad'               => 'Felhasználónév nem tartalmazhat ^ karaktert',
    'handle_label'                 => 'Felhasználónév:',
    'hide_all_user_button'         => 'Minden üzenet elrejtése ettől a felhasználótól',
    'last_login_label'             => 'Legutóbbi bejelentkezés:',
    'last_write_label'             => 'Utolsó írási művelet:',
    'level_admin'                  => 'Adminisztrátor',
    'level_editor'                 => 'Szerkesztő',
    'level_expert'                 => 'Szakértő',
    'level_for_category'           => '^1 a(z) ^2 kategóriához',
    'level_in_general'             => 'általánosságban',
    'level_moderator'              => 'Moderátor',
    'level_super'                  => 'Szuper adminisztrátor',
    'location'                     => 'Hely',
    'log_in_to_access'             => 'Most már ^1bejelentkezhetsz^2 a fiókodba.',
    'login_button'                 => 'Bejelentkezés',
    'login_limit'                  => 'Túl sok bejelentkezési próbálkozás - kérjük próbálkozz újra egy óra múlva',
    'login_title'                  => 'Bejelentkezés',
    'mass_mailings'                => 'Tömeges levelezés:',
    'mass_mailings_explanation'    => 'Feliratkozás a minden felhasználónak szánt emailekre',
    'member_for'                   => 'Tag:',
    'member_type'                  => 'Típus:',
    'new_password_1'               => 'Új jelszó:',
    'new_password_2'               => 'Ismételd meg az új jelszót:',
    'no_blocked_users'             => 'Nincs blokkolt felhasználó',
    'no_permission'                => 'Nincs jogosultságod ennek a műveletnek a végrehajtására',
    'old_password'                 => 'Régi jelszó:',
    'only_shown_admins'            => '(csak te és az adminok látják)',
    'only_shown_editors'           => '(csak neked, a szerkesztőknek és a felettük lévőknek látható)',
    'only_shown_experts'           => '(csak neked, a szakértőknek és a felettük lévőknek látható)',
    'only_shown_moderators'        => '(csak te, a moderátorok és az adminok látják)',
    'password_changed'             => 'Jelszó megváltoztatva',
    'password_label'               => 'Jelszó:',
    'password_min'                 => 'A jelszónak legalább ^ karakter hosszúnak kell lennie',
    'password_mismatch'            => 'Az új jelszavak nem egyeznek meg',
    'password_none'                => 'Nincs. A közvetlen bejelentkezéshez állíts be alább egy jelszót.',
    'password_sent'                => 'Az új jelszavadat elküldtük neked emailben',
    'password_to_set'              => 'Kérjük állítsd be a profilodon',
    'password_wrong'               => 'Hibás jelszó',
    'private_messages'             => 'Privát üzenetek:',
    'private_messages_explanation' => 'Engedélyezd a felhasználóknak, hogy emailt küldhessenek (a címed megtekintése nélkül)',
    'profile_saved'                => 'Profil elmentve',
    'register_button'              => 'Regisztráció',
    'register_limit'               => 'Túl sok regisztráció - kérjük próbálkozz újra egy óra múlva',
    'register_suspended'           => 'Az új felhasználók regisztrációja ideiglenesen felfüggesztésre került. Próbáld újra hamarosan.',
    'register_title'               => 'Új felhasználó regisztrálása',
    'registered_label'             => 'Regisztrálva:',
    'registered_user'              => 'Regisztrált felhasználó',
    'remember'                     => 'Emlékezz',
    'remember_label'               => 'Emlékezz rám ezen a számítógépen',
    'remove_avatar'                => 'Avatar törlése:',
    'reset_title'                  => 'Elfelejtett jelszó visszaállítása',
    'save_profile'                 => 'Profil mentése',
    'save_user'                    => 'Felhasználó mentése',
    'send_confirm_button'          => 'Megerősítő link küldése',
    'send_reset_button'            => 'Jelszó-visszaállító email küldése',
    'send_reset_note'              => 'Egy utasításokat tartalmazó emailt küldünk a címedre.',
    'special_users'                => 'Különleges felhasználók',
    'terms_not_accepted'           => 'Ezt be kell jelölni.',
    'unblock_user_button'          => 'Felhasználó feloldása',
    'unsubscribe'                  => 'Leiratkozás:',
    'unsubscribe_complete'         => 'Leiratkoztál a(z) ^0 által küldött tömeges levelezésről. Bármikor újra feliratkozhatsz a ^1profilodon^2 keresztül.',
    'unsubscribe_title'            => 'Leiratkozás',
    'unsubscribe_wrong_log_in'     => 'A kód nem helyes - kérjük ^1jelentkezz be^2 a leiratkozáshoz',
    'user_blocked'                 => '(blokkolt)',
    'user_not_found'               => 'Felhasználó nem található',
    'wall_posts'                   => 'Fali posztok:',
    'wall_posts_explanation'       => 'Felhasználói posztok engedélyezése a faladon (emailben is értesítünk róla)',
    'website'                      => 'Weboldal',
    'x_ago_from_y'                 => 'ennyi ideje: ^1, tőle: ^2',
);
