<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

return array(
    '1_answer_title'           => '1 válasz',
    'a_convert_to_c'           => 'Válasz konvertálása hozzászólássá',
    'a_convert_to_c_on'        => 'Válasz konvertálása hozzászólássá itt:',
    'a_convert_warn'           => 'Figyelem: Ez az átalakítás nem vonható vissza.',
    'a_convert_warn_cs'        => 'Figyelem: Ez az átalakítás nem vonható vissza, és a válaszhoz érkezett hozzászólásokat is át fogja helyezni.',
    'a_notify_email'           => 'Ide kérek emailt, ha a válaszom kiválasztásra kerül vagy hozzászólnak:',
    'a_notify_label'           => 'Kérek emailt, ha a válaszom kiválasztásra kerül vagy hozzászólnak',
    'a_notify_x_label'         => 'Kérek emailt (^), ha a válaszom kiválasztásra kerül vagy hozzászólnak',
    'a_waiting_your_approval'  => 'Ez a válasz a te elfogadásodra vár',
    'a_your_waiting_approval'  => 'A válaszod hamarosan felülbírálásra és elfogadásra kerül.',
    'add_answer_button'        => 'Válasz hozzáadása',
    'add_comment_button'       => 'Hosszászólás hozzáadása',
    'add_q_favorites'          => 'Kérdés hozzáadása a kedvenceimhez',
    'anon_name_label'          => 'Megjelenő neved (tetszőleges):',
    'answer_button'            => 'válasz',
    'answer_limit'             => 'Túl sok válasz érkezett - kérjük próbálkozz újra egy óra múlva',
    'answer_must_be_approved'  => 'A fiókodat el kell fogadjuk, mielőtt kérdést tehetnél fel. Kérjük várj, vagy ^1adj meg több adatot^2.',
    'answer_must_confirm'      => 'Kérjük ^5erősítsd meg az email címed^6, hogy válaszolhass erre a kérdésre.',
    'answer_must_login'        => 'Kérjük ^1jelentkezz be^2 vagy ^3regisztrálj^4, hogy válaszolhass erre a kérdésre.',
    'answer_q_popup'           => 'Kérdés megválaszolása',
    'approve_a_popup'          => 'Válasz elfogadása',
    'approve_button'           => 'elfogad',
    'approve_c_popup'          => 'Hozzászólás elfogadása',
    'approve_q_popup'          => 'Kérdés elfogadása',
    'ask_button'               => 'Kérdés feltevése',
    'ask_follow_from_a'        => 'A kérdésed ehhez a válaszhoz kapcsolódik:',
    'ask_follow_title'         => 'Kapcsolódó kérdés feltevése',
    'ask_limit'                => 'Túl sok kérdés - kérjük próbálkozz újra egy óra múlva',
    'ask_must_be_approved'     => 'A fiókodat el kell fogadjuk, mielőtt kérdést tehetnél fel. Kérjük várj, vagy ^1adj meg több adatot^2.',
    'ask_must_confirm'         => 'Kérjük ^5erősítsd meg az email címed^6 hogy megválaszolhasd ezt a kérdést.',
    'ask_must_login'           => 'Kérjük ^1jelentkezz be^2 vagy ^3regisztrálj^4, hogy feltehesd a kérdést.',
    'ask_same_q'               => 'Mielőtt továbblépsz, kérjük nézd meg, hogy a kérdésedet nem tette-e már fel valaki:',
    'ask_title'                => 'Kérdés feltevése',
    'c_notify_email'           => 'Ide kérek emailt, ha a hozzászólásom után érkezik komment:',
    'c_notify_label'           => 'Kérek emailt, ha a hozzászólásom után érkezik komment',
    'c_notify_x_label'         => 'Kérek emailt (^), ha a hozzászólásom után érkezik komment:',
    'c_waiting_your_approval'  => 'Ez a hozzászólás az elfogadásodra vár',
    'c_your_waiting_approval'  => 'A válaszod hamarosan felülbírálásra és elfogadásra kerül.',
    'category_ask_not_allowed' => 'Nincs jogosultságod, hogy ebben a kategóriában tegyél fel kérdést',
    'category_js_note'         => 'A kategória kiválasztásához engedélyezd a Javascriptet a böngésződben.',
    'category_required'        => 'Válassz egy kategóriát',
    'claim_a_popup'            => 'Kapcsold ezt a választ a felhasználói fiókodhoz',
    'claim_button'             => 'Ezt én írtam',
    'claim_c_popup'            => 'Kapcsold ezt a hozzászólást a felhasználói fiókodhoz',
    'claim_q_popup'            => 'Kapcsold ezt a kérdést a felhasználói fiókodhoz',
    'clear_flags_button'       => 'jelentések törlése',
    'clear_flags_popup'        => 'Minden felhasználó jelentésének törlése',
    'close_button'             => 'bezárás',
    'close_duplicate'          => 'Ez a kérdés már létezik',
    'close_duplicate_error'    => 'A kérdés duplikátuma nem található - próbálj meg egy másik kérdés URL-jében található számot beírni, pl. 123.',
    'close_form_button'        => 'Kérdés lezárása',
    'close_form_title'         => 'Lezárom ezt a kérdést',
    'close_original_note'      => 'Beírhatod egy másik kérdés számát annak URL-jéből is, pl. 123.',
    'close_original_title'     => 'Az eredeti kérdés URL-je:',
    'close_q_popup'            => 'Kérdés lezárása új válaszok elől',
    'close_reason_title'       => 'A kérdés lezárásának oka, vagy a kérdés duplikátumának URL-je:',
    'closed_as_duplicate'      => 'egy másik kérdés duplikátumaként lezárva:',
    'closed_with_note'         => 'megjegyzéssel lezárva:',
    'comment_a_popup'          => 'Hozzászólás a válaszhoz',
    'comment_button'           => 'hozzászólás',
    'comment_limit'            => 'Túl sok hozzászólás - kérjük próbálkozz újra egy óra múlva',
    'comment_must_be_approved' => 'A fiókodat el kell fogadjuk, mielőtt hozzászólást írhatnál. Kérjük várj, vagy ^1adj meg több adatot^2.',
    'comment_must_confirm'     => 'Kérjük ^5erősítsd meg e-mail címed^6, hogy hozzászólhass.',
    'comment_must_login'       => 'Kérjük ^1jelentkezz be^2 vagy ^3regisztrálj^4, hogy hozzászólhass.',
    'comment_on_a'             => 'Válaszon: ',
    'comment_on_q'             => 'Kérdésen: ',
    'comment_q_popup'          => 'Hozzászólás ehhez a kérdéshez',
    'delete_a_popup'           => 'Válasz végleges törlése',
    'delete_button'            => 'törlés',
    'delete_c_popup'           => 'Hozzászólás végleges törlése',
    'delete_q_popup'           => 'Kérdés végleges törlése',
    'duplicate_content'        => 'A beküldött tartalmad duplikátumnak tűnik.',
    'edit_a_popup'             => 'Válasz szerkesztése',
    'edit_a_title'             => 'Válasz szerkesztése',
    'edit_button'              => 'szerkesztés',
    'edit_c_popup'             => 'Hozzászólás szerkesztése',
    'edit_c_title'             => 'Hozzászólás szerkesztése',
    'edit_must_confirm'        => 'Kérjük ^5erősítsd meg az email címed^6 a szerkesztéshez.',
    'edit_must_login'          => 'Kérjük ^1lépj be^2 vagy ^3regisztrálj^4 a szerkesztéshez.',
    'edit_q_popup'             => 'Kérdés szerkesztése',
    'edit_q_title'             => 'Kérdés szerkesztése',
    'example_tags'             => 'Címke példák: ',
    'flag_a_popup'             => 'Válasz jelentése kéretlen tartalomként',
    'flag_button'              => 'jelentés',
    'flag_c_popup'             => 'Hozzászólás jelentése kéretlen tartalomként',
    'flag_hide_button'         => 'jelentés és elrejtés',
    'flag_limit'               => 'Túl sok hozzászólás megjelölve - próbálkozzál újra egy órán belül',
    'flag_must_confirm'        => 'Kérjük ^5erősítsd meg email címedet^6 a posztok megjelöléséhez.',
    'flag_must_login'          => 'Kérjük ^1jelentkezz be^2 vagy ^3regisztrálj^4 a posztok megjelöléséhez.',
    'flag_not_allowed'         => 'Ennek a megjelölése nincs engedélyezve',
    'flag_q_popup'             => 'Jelöld meg ezt a kérdést spamnek vagy nem megfelelőnek',
    'follow_a_popup'           => 'Kérdezz egy új kérdést erre a válaszra vonatkozóan',
    'follow_button'            => 'kérdezz kapcsolódó kérdést',
    'follows_a'                => 'ehhez a válaszhoz kapcsolódik:',
    'follows_q'                => 'a kérdésről:',
    'hide_a_popup'             => 'Válasz elrejtése',
    'hide_button'              => 'elrejtés',
    'hide_c_popup'             => 'Hozzászólás elrejtése',
    'hide_q_popup'             => 'Kérdés elrejtése',
    'matching_tags'            => 'Megfelelő címkék: ',
    'max_tags_x'               => 'A címkék maximális engedélyezett száma ^',
    'min_tags_x'               => 'Adj meg legalább ^ címkét',
    'notify_email_note'        => 'Adatvédelem: Az email címed csak az ilyen értesítések küldésére szolgál.',
    'q_category_label'         => 'Kategória:',
    'q_content_label'          => 'További információ a kérdéshez:',
    'q_hidden_author'          => 'Ezt a kérdést a szerzője elrejtette',
    'q_hidden_flagged'         => 'Ez a kérdés jelentett és rejtett',
    'q_hidden_other'           => 'Ez a kérdés rejtve van',
    'q_notify_email'           => 'Ide kérek emailt, ha a kérdésemre válasz vagy hozzászólás érkezik:',
    'q_notify_label'           => 'Kérek emailt, ha a kérdésemre válasz vagy hozzászólás érkezik',
    'q_notify_x_label'         => 'Kérek emailt (^), ha a kérdésemre válasz vagy hozzászólás érkezik',
    'q_tags_comma_label'       => 'Címkék - vessző (,) használata elválasztóként:',
    'q_tags_label'             => 'Címkék - kötőjel használata szavak kombinálásához:',
    'q_title_label'            => 'A kérdés egy mondatban:',
    'q_waiting_approval'       => 'Ez a kérdés jóváhagyásra vár',
    'q_waiting_your_approval'  => 'Ez a kérdés a jóváhagyásodra vár',
    'q_your_waiting_approval'  => 'A kérdésedet hamarosan ellenőrizzük és elfogadjuk.',
    'recat_button'             => 'újrakategorizálás',
    'recat_popup'              => 'Kérdés kategóriájának megváltoztatása',
    'recat_q_title'            => 'Kérdés újrakategorizálása',
    'reject_a_popup'           => 'Válasz elutasítása',
    'reject_button'            => 'elutasítás',
    'reject_c_popup'           => 'Hozzászólás elutasítása',
    'reject_q_popup'           => 'Kérdés elutasítása',
    'remove_q_favorites'       => 'Kérdés eltávolítása a kedvenceim közül',
    'reopen_button'            => 'újranyitás',
    'reopen_q_popup'           => 'Kérdés újranyitása',
    'reply_button'             => 'válasz küldése',
    'reply_c_popup'            => 'Válasz írása ehhez a hozzászóláshoz',
    'reshow_a_popup'           => 'Válasz újramegjelenítése',
    'reshow_button'            => 'újramegjelenítés',
    'reshow_c_popup'           => 'Hozzászólás újramegjelenítése',
    'reshow_q_popup'           => 'Kérdés újramegjelenítése',
    'retag_button'             => 'újracímkézés',
    'retag_cat_popup'          => 'Kérdés kategóriájának és címkéinek megváltoztatása',
    'retag_popup'              => 'Kérdés címkéinek megváltoztatása',
    'retag_q_title'            => 'Kérdés újracímkézése',
    'save_silent_label'        => 'Csendes mentés (rejtett marad, hogy szerkesztett tartalom)',
    'select_popup'             => 'Kattints a legjobb válasz kiválasztáshoz',
    'select_text'              => 'Legjobb válasz',
    'show_1_comment'           => '1 hozzászólás mutatása',
    'show_1_previous_comment'  => '1 korábbi hozzászólás mutatása',
    'show_x_comments'          => '^ hozzászólás mutatása',
    'show_x_previous_comments' => '^ korábbi hozzászólás mutatása',
    'unflag_button'            => 'jelző törlése',
    'unflag_popup'             => 'A hozzáadott jelző törlése',
    'unselect_popup'           => 'Kattints a kiválasztás visszavonásához',
    'x_answers_title'          => '^ Válasz',
    'your_answer_title'        => 'A válaszod',
    'your_comment_a'           => 'A hozzászólásod ehhez a válaszhoz:',
    'your_comment_q'           => 'A hozzászólásod ehhez a kérdéshez:',
);
